version: '3.7'

services:
  mysql:
    build:
      context: ./mysql
    restart: always
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/mysql

  wordpress:
    build:
      context: ./wordpress
    restart: always
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - wp:/var/www/html
    depends_on:
      - mysql

  pma:
    build:
      context: ./phpmyadmin
    restart: always
    env_file: .env
    links:
      - mysql
    ports:
      - "8080:80"

volumes:
  db:
  wp:
