version: '3.7'

services:
  mysql:
    build:
      context: ./mysql
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/mysql

  wordpress:
    build:
      context: ./wordpress
    env_file:
      - ./.env
    ports:
      - "8080:80"
    volumes:
      - wp:/var/www/html
    depends_on:
      - mysql

volumes:
  db:
  wp:
